tidy-all:
	cd ./1_xor;go mod tidy
	cd ./2_xor_with_intermediate;go mod tidy
	cd ./3_mnist;go mod tidy
	cd ./4_dog_cats;go mod tidy
	cd ./5_iris_dataset;go mod tidy
	cd ./6_generator;go mod tidy

upgrade-all:
	cd ./1_xor;go get -u github.com/JoshPattman/goras
	cd ./2_xor_with_intermediate;go get -u github.com/JoshPattman/goras
	cd ./3_mnist;go get -u github.com/JoshPattman/goras
	cd ./4_dog_cats;go get -u github.com/JoshPattman/goras
	cd ./5_iris_dataset;go get -u github.com/JoshPattman/goras
	cd ./6_generator;go get -u github.com/JoshPattman/goras